import { Pokemons } from "../components/pokemons";

export const metadata = {
  title: "Pokemons",
  description: "Generated by Next.js",
};

const Home = () => {
  return (
    <div>
      <span>.home</span>
      <Pokemons />
    </div>
  );
};

export default Home;
